#ifndef _CONSTANTS_H
#define _CONSTANTS_H

//screen dimensions
#define SCREEN_WIDTH 512
#define SCREEN_HEIGHT 512
#define MOVEMENT_SPEED 100
#define JUMP_FORCE_DECREMENT 400.0f
#define INITIAL_JUMP_FORCE 400.0f
#define MAP_WIDTH 16
#define MAP_HEIGHT 13
#define GRAVITY 90.0f
#define TILE_WIDTH 32
#define TILE_HEIGHT 32
#define START_HEIGHT 135
#define START_WIDTH 240
#define SCREEN_SHAKE_TIME 0.25f
#define KOOPA_SPRITE_WIDTH 32
#define KOOPA_SPRITE_HEIGHT 30
#define INJURED_TIME 2.5f
#define INITIAL_JUMP_FORCE_KOOPA 100
#define JUMP_FORCE_DECREMENT_KOOPA 100
#define KOOPA_MOVEMENT_SPEED 50
#define ENEMY_TIMER 20
#define ANIMATION_DELAY 30
#define COIN_SPRITE_HEIGHT 20
#define COIN_SPRITE_WIDTH 48

#endif // !_CONSTANTS_H